// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Practitioner struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Title    string    `json:"title"`
	Picture  *string   `json:"picture"`
	Location string    `json:"location"`
	Domains  []*Domain `json:"domains"`
}

type Domain struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Icon       *string `json:"icon"`
	Importance int     `json:"importance"`
}

